const dataPartition = {
    'RTL_Credit_Card_History__c': 'RtlCust:Sales Support Information',
    'RTL_Personal_Loan_History__c': 'RtlCust:Sales Support Information',
    'RTL_Entitled_Privilege2__c': 'RtlCust:MI Benefits',
    'RTL_Privilege2__c': 'RtlCust:MI Benefits',
    'RTL_Lifetime_Code__c': 'RtlCust:Sales Support Information',
    'KYC__c' : 'RtlCust:Sales Support Information',
    'RTL_Lifetime_link__c': 'RtlCust:Sales Support Information',
    'KYC_CCI1_Completed__c': 'RtlCust:Sales Support Information',
    'Consolidate_Status__c': 'RtlCust:Sales Support Information',
    'RTL_CC_STMT_status__c': 'RtlCust:Sales Support Information',
    'RTL_RDC_STMT_status__c': 'RtlCust:Sales Support Information',
    'RTL_C2G_STMT_status__c': 'RtlCust:Sales Support Information',
    'Fna_Product_Interested__c': 'RtlCust:Sales Support Information',
    'Fna_Product_Holding__c': 'RtlCust:Sales Support Information',
    'RTL_4THANA_Info__c': 'RtlCust:Sales Support Information',
    'RTL_4THANA_Fund_AMT__c': 'RtlCust:Sales Support Information',
    'RTL_4THANA_Aggregate_Bond_AMT__c': 'RtlCust:Sales Support Information',
    'RTL_4THANA_Bond_AMT__c': 'RtlCust:Sales Support Information',
    'RTL_4THANA_Short_Bond_AMT__c': 'RtlCust:Sales Support Information',
    'RTL_4THANA_Total_AMT__c': 'RtlCust:Sales Support Information',
    'RTL_OnSite_Service__c': 'RtlCust:Sales Support Information',
    'RTL_OnSite_Service_Update_Date__c': 'RtlCust:Sales Support Information',

    'regisStateTable': 'RtlCust:Sales Support Information',
    'e_statement': 'RtlCust:Sales Support Information',
    'CYC_Campaign_PromoCond_api' : 'RtlCust:MI Benefits'

}

let objectField = {
  Core_Banking_Suggested_Segment__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "Segment",
    value: "Affluent",
    name: "Core_Banking_Suggested_Segment__c",
  },
  Name: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "Customer Name/Company (TH)",
    value: "Retail Full Name 1000",
    name: "Name",
  },
  RTL_OnSite_Service_User_Update__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "On Site Service User Update",
    value: "",
    name: "RTL_OnSite_Service_User_Update__c",
  },
  RTL_OnSite_Service_Update_Date__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "DATE",
    label: "On Site Service Update Date",
    value: "",
    name: "RTL_OnSite_Service_Update_Date__c",
  },
  RTL_OnSite_Service__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "On Site Service",
    value: "",
    name: "RTL_OnSite_Service__c",
  },
  Fna_Product_Holding__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "TEXTAREA",
    label: "Fna Product Holding",
    value: "",
    name: "Fna_Product_Holding__c",
  },
  Fna_Product_Interested__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "TEXTAREA",
    label: "Fna Product Interested",
    value: "",
    name: "Fna_Product_Interested__c",
  },
  RTL_C2G_STMT_status__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "C2G STMT status",
    value: "",
    name: "RTL_C2G_STMT_status__c",
  },
  RTL_RDC_STMT_status__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "RDC STMT status",
    value: "",
    name: "RTL_RDC_STMT_status__c",
  },
  RTL_CC_STMT_status__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "CC STMT status",
    value: "",
    name: "RTL_CC_STMT_status__c",
  },
  Consolidate_Status__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "Consolidate Status",
    value: "",
    name: "Consolidate_Status__c",
  },
  RTL_Privilege2__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "TEXTAREA",
    label: "Current Privileges",
    value: "",
    name: "RTL_Privilege2__c",
  },
  RTL_Entitled_Privilege2__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "TEXTAREA",
    label: "Entitled Privileges",
    value: "",
    name: "RTL_Entitled_Privilege2__c",
  },
  RTL_4THANA_Total_AMT__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "DOUBLE",
    label: "Total",
    value: 0,
    name: "RTL_4THANA_Total_AMT__c",
  },
  RTL_4THANA_Short_Bond_AMT__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "DOUBLE",
    label: "TMB Ultra Short Bond Fund Amount",
    value: 0,
    name: "RTL_4THANA_Short_Bond_AMT__c",
  },
  RTL_4THANA_Bond_AMT__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "DOUBLE",
    label: "TMB Bond Fund Amount",
    value: 0,
    name: "RTL_4THANA_Bond_AMT__c",
  },
  RTL_4THANA_Aggregate_Bond_AMT__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "DOUBLE",
    label: "TMB Aggregate Bond Fund Amount",
    value: 0,
    name: "RTL_4THANA_Aggregate_Bond_AMT__c",
  },
  RTL_4THANA_Fund_AMT__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "DOUBLE",
    label: "TMB Thanaplus Fund Amount",
    value: 0,
    name: "RTL_4THANA_Fund_AMT__c",
  },
  RTL_4THANA_Info__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "4 Thana Information",
    value: "",
    name: "RTL_4THANA_Info__c",
  },
  RTL_Personal_Loan_History__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "Personal Loan History",
    value:
      "ลูกค้าไม่เคยมีวงเงินสินเชื่อบุคคลกับ TMB ก่อน 1 กันยายน 60<br>กรณีลูกค้าสมัครสินเชื่อบุคคล TMB จะได้รับวงเงินดังนี้<br>- รายได้ &lt; 30,000 บาท : วงเงินสูงสุด 1.5 เท่าของรายได้<br>- รายได้ &gt;= 30,000 บาท : วงเงินสูงสุด 5 เท่าของรายได้",
    name: "RTL_Personal_Loan_History__c",
  },
  RTL_Credit_Card_History__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "Credit Card History",
    value:
      "ลูกค้าที่ไม่เคยมีบัตรเครดิต TMB ก่อน 1 กันยายน 2560<br>1. กรณีสมัครบัตรเครดิต TMB So Fast/ So Chill/ So Smart/ Royal Top Brass จะได้รับวงเงินดังนี้<br> - รายได้ &lt; 30,000 : วงเงินสูงสุด 1.5 เท่า<br> - รายได้ 30,000 ขึ้นไป : วงเงินสูงสุด 3 เท่า<br>2. กรณีสมัครบัตรเครดิต TMB ABSOLUTE Visa Signature จะได้รับวงเงินดังนี้<br> - รายได้ 100,000 ขึ้นไป : วงเงินสูงสุด 5 เท่า",
    name: "RTL_Credit_Card_History__c",
  },
  RTL_Lifetime_link__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "Lifetime link",
    value:
      '<a href="http://lfp.8interactive.co.th/" target="_blank">ดูข้อมูล Lifetime ของลูกค้า</a>',
    name: "RTL_Lifetime_link__c",
  },
  RTL_Lifetime_Code__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "Lifetime Reference code",
    value: "",
    name: "RTL_Lifetime_Code__c",
  },
  KYC_CCI1_Completed__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "PICKLIST",
    label: "KYC CCI1 Completed",
    value: "",
    name: "KYC_CCI1_Completed__c",
  },
  KYC__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "KYC",
    value: "",
    name: "KYC__c",
  },
  TMB_Customer_ID_PE__c: {
    isAccessible: true,
    inlineHelpText: "",
    type: "STRING",
    label: "TMB Customer ID",
    value: "001100000000000000000000051187",
    name: "TMB_Customer_ID_PE__c",
  },
  regisStateTable: {
    isAccessible: false,
  },
  e_statement: {
    isAccessible: false,
  },
  CYC_Campaign_PromoCond_api: {
    isAccessible: false,
  },
};

for(const key in objectField){
    objectField[key].isAccessible = false;
    //console.log(key);
}
console.log(objectField);
